import React from "react";
import {
  FiShield, FiPrinter, FiPlus, FiAlertTriangle, FiCheckCircle,
  FiCalendar, FiFileText, FiHeart, FiAward, FiSearch
} from "react-icons/fi";
import C from "../../constants/colors";
import S from "../../constants/styles";
import ProtocolExCard from "../../components/ProtocolExCard";
import StoryboardPlayer from "../../components/StoryboardPlayer";
import { CLINIC_ONLY_CODES } from "./constants";

export default function ProtocolResults({ protocol, setProtocol, setWizardStep, removeExercise, setAddingToWeek, setShowAddModal, showStoryboard, setShowStoryboard }) {
  // Group weeks by phase using _phaseInfo from protocol generator
  const phaseGroups = [];
  let currentPhase = null;
  (protocol.weeks || []).forEach(week => {
    const info = week.exercises?.[0]?._phaseInfo;
    if (info && (!currentPhase || currentPhase.number !== info.number)) {
      currentPhase = { ...info, weeks: [week], startWeek: week.week_number, endWeek: week.week_number };
      phaseGroups.push(currentPhase);
    } else if (currentPhase) {
      currentPhase.weeks.push(week);
      currentPhase.endWeek = week.week_number;
    } else {
      // Fallback if no _phaseInfo
      currentPhase = { number: 1, name: "Recovery", goal: "", weeks: [week], startWeek: week.week_number, endWeek: week.week_number };
      phaseGroups.push(currentPhase);
    }
  });
  const phaseColors = [C.red, C.amber, C.teal, C.green];
  const totalWeeks = protocol.protocol_length_weeks || protocol.weeks?.length || 8;

  return (
    <div className="print-protocol">
      {/* Storyboard Player Modal */}
      {showStoryboard && <StoryboardPlayer exerciseCode={showStoryboard} onClose={() => setShowStoryboard(null)} />}
      {/* ── CDSS / Veterinary Oversight Disclaimer Banner ── */}
      <div style={{
        padding: "12px 20px", marginBottom: 10, borderRadius: 8,
        background: "linear-gradient(135deg, #1E3A5F 0%, #0A2540 100%)",
        border: "1px solid #2E4A6F",
        display: "flex", alignItems: "center", gap: 12,
      }}>
        <FiShield size={18} style={{ color: "#FBBF24", flexShrink: 0 }} />
        <div>
          <div style={{ fontSize: 11, fontWeight: 800, color: "#FBBF24", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 2 }}>
            Clinical Decision-Support Output — Veterinary Review Required
          </div>
          <div style={{ fontSize: 10, color: "rgba(255,255,255,0.8)", lineHeight: 1.5 }}>
            This protocol is generated by a clinical decision-support system (CDSS). It does not constitute a diagnosis, prescription, or veterinary-client-patient relationship (VCPR). All content must be reviewed and approved by a licensed veterinarian before being applied to a patient.
          </div>
        </div>
      </div>

      {/* ── Print / Export Action Bar ── */}
      <div className="no-print" style={{
        display: "flex", gap: 8, marginBottom: 10, justifyContent: "flex-end",
      }}>
        <button onClick={() => window.print()} style={{
          ...S.btn("outline"), fontSize: 11, padding: "6px 14px",
          display: "flex", alignItems: "center", gap: 6,
        }}>
          <FiPrinter size={12} /> Print Protocol
        </button>
        <button onClick={() => {
          setProtocol(null);
          setWizardStep(1);
        }} style={{
          ...S.btn("outline"), fontSize: 11, padding: "6px 14px",
          display: "flex", alignItems: "center", gap: 6,
        }}>
          <FiPlus size={12} /> New Protocol
        </button>
      </div>

      {/* ── Red-Flag Warnings (if any) ── */}
      {protocol.red_flag_warnings && protocol.red_flag_warnings.length > 0 && (
        <div style={{
          padding: "14px 20px", marginBottom: 10, borderRadius: 8,
          background: "linear-gradient(135deg, #7F1D1D 0%, #450A0A 100%)",
          border: `1px solid ${C.red}`,
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <FiAlertTriangle size={16} style={{ color: "#FCA5A5", flexShrink: 0 }} />
            <span style={{ fontSize: 12, fontWeight: 800, color: "#FCA5A5", textTransform: "uppercase", letterSpacing: "1px" }}>
              Clinical Red Flags Detected
            </span>
          </div>
          {protocol.red_flag_warnings.map((w, i) => (
            <div key={i} style={{ fontSize: 11, color: "#FECACA", lineHeight: 1.6, marginBottom: 4, paddingLeft: 24 }}>
              {w}
            </div>
          ))}
        </div>
      )}

      {/* ── Protocol Summary Header ── */}
      <div style={{
        ...S.card, borderTop: `4px solid ${C.teal}`,
        background: `linear-gradient(135deg, ${C.surface} 0%, ${C.tealLight}15 100%)`,
        padding: "24px 28px",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: C.teal, textTransform: "uppercase", letterSpacing: "1.5px", marginBottom: 4 }}>
              {protocol.protocol_name || "Rehabilitation Protocol"} — {(protocol.protocol_type || "").toUpperCase()}
            </div>
            <h2 style={{ margin: "0 0 8px", color: C.navy, fontSize: 24, fontWeight: 800 }}>
              {protocol.patient_name}
            </h2>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 8 }}>
              <span style={S.badge("blue")}>{protocol.condition}</span>
              <span style={S.badge("green")}>{protocol.affected_region}</span>
              <span style={S.badge("blue")}>{totalWeeks} Weeks</span>
              <span style={{ ...S.badge("green"), background: "#EDE9FE", color: "#6B21A8" }}>{phaseGroups.length} Phases</span>
            </div>
            <p style={{ margin: 0, color: C.textLight, fontSize: 11 }}>
              Protocol ID: {protocol.patient_id} · Generated {new Date(protocol.generated_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} · {protocol.total_exercises} exercises in library
            </p>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 36, fontWeight: 800, color: C.navy }}>{totalWeeks}</div>
            <div style={{ fontSize: 9, fontWeight: 700, color: C.textLight, textTransform: "uppercase", letterSpacing: "1px" }}>Week Program</div>
            <div style={{ display: "flex", gap: 6, marginTop: 10 }}>
              <button style={{ ...S.btn("primary"), fontSize: 11, padding: "6px 16px" }}
                onClick={() => { setProtocol(null); setWizardStep(1); }}>
                <FiFileText size={12} /> New Protocol
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* ── Phase Timeline Bar ── */}
      {phaseGroups.length > 1 && (
        <div style={{ ...S.card, padding: "20px 24px" }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: C.textLight, textTransform: "uppercase", letterSpacing: "0.8px", marginBottom: 12 }}>
            Phase Timeline — Gated Progression
          </div>
          <div style={{ display: "flex", borderRadius: 8, overflow: "hidden", height: 38, background: C.bg, border: `1px solid ${C.border}` }}>
            {phaseGroups.map((phase, i) => {
              const widthPct = (phase.weeks.length / totalWeeks) * 100;
              return (
                <div key={i} style={{
                  width: `${widthPct}%`, background: `linear-gradient(135deg, ${phaseColors[i] || C.teal}, ${phaseColors[i] || C.teal}CC)`,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 10, fontWeight: 700, color: "#fff", letterSpacing: "0.3px",
                  minWidth: 80, borderRight: i < phaseGroups.length - 1 ? "2px solid rgba(255,255,255,0.5)" : "none",
                }}>
                  P{phase.number}: {phase.name}
                </div>
              );
            })}
          </div>
          <div style={{ display: "flex", marginTop: 6 }}>
            {phaseGroups.map((phase, i) => (
              <div key={i} style={{
                flex: phase.weeks.length / totalWeeks,
                textAlign: "center", fontSize: 10, color: C.textLight, fontWeight: 500,
              }}>
                Wk {phase.startWeek}–{phase.endWeek}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Phase Sections with Exercises ── */}
      {phaseGroups.map((phase, phaseIdx) => (
        <div key={phaseIdx} style={{ marginBottom: 24 }}>

          {/* Phase Header Card */}
          <div style={{
            ...S.card, borderLeft: `5px solid ${phaseColors[phaseIdx] || C.teal}`,
            background: `linear-gradient(135deg, ${C.surface} 0%, ${phaseColors[phaseIdx] || C.teal}08 100%)`,
            marginBottom: 8,
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
              <div>
                <div style={{
                  fontSize: 10, fontWeight: 800, color: phaseColors[phaseIdx] || C.teal,
                  textTransform: "uppercase", letterSpacing: "1.5px", marginBottom: 4,
                }}>
                  Phase {phase.number} | Weeks {phase.startWeek}–{phase.endWeek}
                </div>
                <h3 style={{ margin: "0 0 6px", fontSize: 18, fontWeight: 800, color: C.navy }}>
                  {phase.name}
                </h3>
                {phase.goal && (
                  <p style={{ margin: "0 0 4px", fontSize: 12, color: C.textMid, lineHeight: 1.6 }}>
                    {phase.goal}
                  </p>
                )}
              </div>
              <div style={{
                fontSize: 11, fontWeight: 700, color: phaseColors[phaseIdx] || C.teal,
                background: (phaseColors[phaseIdx] || C.teal) + "14",
                padding: "4px 12px", borderRadius: 6,
              }}>
                {phase.weeks.length} wk{phase.weeks.length !== 1 ? "s" : ""}
              </div>
            </div>

            {/* Contraindications */}
            {phase.contraindications && (
              <div style={{
                marginTop: 12, padding: "10px 14px", background: C.redBg,
                border: `1px solid ${C.red}22`, borderRadius: 6,
                display: "flex", gap: 8, alignItems: "flex-start",
              }}>
                <FiAlertTriangle size={13} style={{ color: C.red, flexShrink: 0, marginTop: 1 }} />
                <div style={{ fontSize: 11, color: C.red, lineHeight: 1.5 }}>
                  <strong>Contraindications:</strong> {phase.contraindications}
                </div>
              </div>
            )}
          </div>

          {/* Weekly Cards within this phase */}
          {phase.weeks.map((week) => {
            const globalWeekIdx = (protocol.weeks || []).indexOf(week);
            return (
              <div key={week.week_number} style={{
                ...S.card, borderLeft: `3px solid ${(phaseColors[phaseIdx] || C.teal)}44`,
                marginLeft: 16, marginBottom: 8,
              }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
                  <h4 style={{ margin: 0, fontSize: 13, fontWeight: 700, color: C.navy }}>
                    Week {week.week_number}
                  </h4>
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span style={{ fontSize: 10, color: C.textLight }}>
                      {week.exercises.length} exercise{week.exercises.length !== 1 ? "s" : ""}
                    </span>
                    <button
                      onClick={() => { setAddingToWeek(globalWeekIdx); setShowAddModal(true); }}
                      style={{ ...S.btn("primary"), padding: "4px 12px", fontSize: 10 }}>
                      <FiPlus size={11} /> Add
                    </button>
                  </div>
                </div>
                <div style={S.grid(3)}>
                  {week.exercises.map((ex, exIdx) => (
                    <ProtocolExCard
                      key={exIdx}
                      entry={{ exercise: ex, sets: ex.sets, reps: ex.reps, frequency_per_day: ex.frequency, duration_seconds: ex.duration_minutes ? ex.duration_minutes * 60 : null, notes: ex.notes }}
                      onRemove={() => removeExercise(globalWeekIdx, exIdx)}
                      onOpenStoryboard={setShowStoryboard}
                    />
                  ))}
                </div>
              </div>
            );
          })}

          {/* Progression Gate — between phases */}
          {phaseIdx < phaseGroups.length - 1 && phase.progressionCriteria && (
            <div style={{
              ...S.card, background: C.greenBg, border: `1px solid ${C.green}33`,
              borderLeft: `4px solid ${C.green}`, marginTop: 4,
            }}>
              <div style={{
                fontSize: 10, fontWeight: 800, color: C.green,
                textTransform: "uppercase", letterSpacing: "1px", marginBottom: 6,
                display: "flex", alignItems: "center", gap: 6,
              }}>
                <FiCheckCircle size={12} />
                Progression Gate — Advance to Phase {phaseGroups[phaseIdx + 1].number}: {phaseGroups[phaseIdx + 1].name}
              </div>
              <p style={{ margin: 0, fontSize: 12, color: C.green, lineHeight: 1.6 }}>
                <strong>Patient must demonstrate:</strong> {phase.progressionCriteria}
              </p>
              <div style={{ marginTop: 10, display: "flex", alignItems: "center", gap: 6 }}>
                <FiCalendar size={11} style={{ color: C.green }} />
                <span style={{ fontSize: 11, fontWeight: 600, color: C.green }}>
                  Schedule re-evaluation at Week {phase.endWeek}
                </span>
              </div>
            </div>
          )}
        </div>
      ))}

      {/* ── Home Exercise Program (HEP) — Client Take-Home ── */}
      {(() => {
        const hepByPhase = {};
        (protocol.weeks || []).forEach(week => {
          const phaseInfo = week.exercises?.[0]?._phaseInfo;
          const phaseName = phaseInfo?.name || "Phase 1";
          const phaseNum = phaseInfo?.number || 1;
          if (!hepByPhase[phaseNum]) hepByPhase[phaseNum] = { name: phaseName, exercises: new Map() };
          (week.exercises || []).forEach(ex => {
            if (!CLINIC_ONLY_CODES.has(ex.code)) {
              hepByPhase[phaseNum].exercises.set(ex.code, ex);
            }
          });
        });
        return (
          <div style={{
            ...S.card, borderTop: `3px solid ${C.green}`,
            background: `linear-gradient(135deg, ${C.surface} 0%, ${C.greenBg} 100%)`,
          }} className="hep-section">
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <FiHeart size={14} style={{ color: C.green }} />
                <span style={{ fontSize: 13, fontWeight: 800, color: C.navy, textTransform: "uppercase", letterSpacing: "0.5px" }}>
                  Home Exercise Program (HEP)
                </span>
              </div>
              <span style={{ ...S.badge("green"), fontSize: 10 }}>Client Take-Home</span>
            </div>
            <p style={{ fontSize: 11, color: C.textMid, marginBottom: 14, lineHeight: 1.6, background: C.greenBg, padding: "10px 14px", borderRadius: 6 }}>
              These exercises are safe to perform at home under the guidance provided. Clinic-only interventions (laser, electrical stimulation, ultrasound, aquatic therapy) are excluded. Always follow your veterinarian's specific instructions and stop any exercise that causes pain or distress.
            </p>
            {Object.entries(hepByPhase).map(([phaseNum, phase]) => (
              <div key={phaseNum} style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: C.navy, marginBottom: 8,
                  padding: "4px 10px", background: C.tealLight, borderRadius: 4, display: "inline-block" }}>
                  Phase {phaseNum}: {phase.name}
                </div>
                <div style={S.grid(2)}>
                  {[...phase.exercises.values()].slice(0, 10).map((ex, i) => (
                    <div key={i} style={{
                      padding: "10px 14px", background: "#fff",
                      border: `1px solid ${C.border}`, borderRadius: 8,
                    }}>
                      <div style={{ fontWeight: 700, fontSize: 12, color: C.navy }}>{ex.name || ex.exercise?.name}</div>
                      <div style={{ fontSize: 11, color: C.textMid, marginTop: 4 }}>
                        {ex.sets && `${ex.sets}`}{ex.reps && ` × ${ex.reps}`}
                        {ex.duration_seconds && ` · ${ex.duration_seconds >= 60 ? `${ex.duration_seconds / 60} min` : `${ex.duration_seconds}s`}`}
                        {ex.frequency_per_day && ` · ${ex.frequency_per_day}×/day`}
                      </div>
                      {ex.notes && <div style={{ fontSize: 10, color: C.textLight, marginTop: 3, fontStyle: "italic" }}>{ex.notes}</div>}
                    </div>
                  ))}
                </div>
              </div>
            ))}
            <div style={{ padding: "8px 12px", background: C.amberBg, border: `1px solid ${C.amber}33`,
              borderRadius: 6, fontSize: 10, color: C.amber, fontWeight: 600, marginTop: 8 }}>
              If your pet shows signs of pain, limping, swelling, or reluctance during any exercise, stop immediately and contact your veterinarian.
            </div>
          </div>
        );
      })()}

      {/* ── Veterinary Sign-Off Section ── */}
      <div style={{
        ...S.card, borderTop: `3px solid ${C.navy}`,
        background: `linear-gradient(135deg, ${C.surface} 0%, #F0F4F8 100%)`,
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}>
          <FiAward size={14} style={{ color: C.navy }} />
          <span style={{ fontSize: 13, fontWeight: 800, color: C.navy, textTransform: "uppercase", letterSpacing: "0.5px" }}>
            Veterinary Review & Approval
          </span>
        </div>
        <div style={S.grid(2)}>
          <div>
            <label style={{ fontSize: 10, fontWeight: 600, color: C.textMid, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 4, display: "block" }}>
              Reviewed By (Licensed Veterinarian)
            </label>
            <input style={{ ...S.input, borderColor: C.navy + "44" }} placeholder="DVM name, credentials, license #" />
          </div>
          <div>
            <label style={{ fontSize: 10, fontWeight: 600, color: C.textMid, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 4, display: "block" }}>
              Date Reviewed
            </label>
            <input style={{ ...S.input, borderColor: C.navy + "44" }} type="date" defaultValue={new Date().toISOString().split("T")[0]} />
          </div>
        </div>
        <div style={{ marginTop: 12 }}>
          <label style={{ fontSize: 10, fontWeight: 600, color: C.textMid, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 4, display: "block" }}>
            Clinical Notes / Modifications
          </label>
          <textarea style={{ ...S.input, minHeight: 48, resize: "vertical" }} placeholder="Document any protocol modifications, patient-specific adjustments, or clinical rationale..." />
        </div>
        <div style={{
          marginTop: 12, padding: "8px 14px", background: C.amberBg,
          border: `1px solid ${C.amber}33`, borderRadius: 6,
          fontSize: 10, color: C.amber, fontWeight: 600,
        }}>
          This protocol must be reviewed and approved by a licensed veterinarian before being applied to a patient. Unsigned protocols are for reference only.
        </div>
      </div>

      {/* ── Legal Disclaimer & ACVSMR Standards Footer ── */}
      <div style={{
        ...S.card, background: "#0A2540", border: "1px solid #1E3A5F",
        padding: "16px 20px",
      }}>
        <div style={{ fontSize: 10, color: "rgba(255,255,255,0.5)", lineHeight: 1.7 }}>
          <strong style={{ color: "rgba(255,255,255,0.7)" }}>DISCLAIMER:</strong> This document is generated by K9 Rehab Pro, a clinical decision-support system (CDSS). It does not establish a veterinarian-client-patient relationship (VCPR), provide a medical diagnosis, or replace in-person veterinary examination. All rehabilitation protocols must be reviewed, modified as clinically appropriate, and approved by a licensed veterinarian before implementation. The platform owner assumes no liability for clinical outcomes resulting from protocol application without proper veterinary oversight.
        </div>

        <div style={{ marginTop: 10, paddingTop: 10, borderTop: "1px solid rgba(255,255,255,0.08)" }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: "rgba(255,255,255,0.5)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 6 }}>
            Practice-Type Applicability
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "6px 16px", fontSize: 9, color: "rgba(255,255,255,0.45)", lineHeight: 1.6 }}>
            <div><strong style={{ color: "rgba(255,255,255,0.6)" }}>General Practice:</strong> Protocols require oversight by attending DVM. Refer complex cases to CCRP/CCRT-certified clinicians.</div>
            <div><strong style={{ color: "rgba(255,255,255,0.6)" }}>Rehabilitation Centers:</strong> Intended for use by CCRP, CCRT, or ACVSMR-certified professionals with direct patient access.</div>
            <div><strong style={{ color: "rgba(255,255,255,0.6)" }}>Specialty Hospitals:</strong> Integrate with existing treatment plans. Coordinate with surgical, neurology, and oncology teams as indicated.</div>
            <div><strong style={{ color: "rgba(255,255,255,0.6)" }}>Universities:</strong> Suitable for clinical teaching under faculty supervision. Not for unsupervised student application.</div>
          </div>
        </div>

        <div style={{ marginTop: 10, paddingTop: 10, borderTop: "1px solid rgba(255,255,255,0.1)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ fontSize: 9, color: "rgba(255,255,255,0.4)", letterSpacing: "0.5px" }}>
            Protocol generated per ACVSMR standards · Millis & Levine methodology · Evidence-based exercise selection
          </div>
          <div style={{ fontSize: 9, color: "rgba(255,255,255,0.3)" }}>
            K9 Rehab Pro™ · Clinical Decision-Support System
          </div>
        </div>
      </div>
    </div>
  );
}
