-- K9 Rehab Pro: Exercises Seed
-- Run in Supabase SQL Editor

INSERT INTO exercises (slug, name, category, description, difficulty, body_region) VALUES
  ('prom-stifle', 'Passive Range of Motion - Stifle', 'Passive Therapy', 'Gentle manual manipulation of the stifle joint through available range to maintain joint mobility and prevent contracture.', 'Easy', 'multi'),
  ('prom-hip', 'Passive Range of Motion - Hip', 'Passive Therapy', 'Manual hip joint mobilization to maintain hip flexion/extension and prevent muscle contracture.', 'Easy', 'multi'),
  ('massage-thera', 'Therapeutic Massage', 'Passive Therapy', 'Manual soft tissue mobilization to reduce muscle tension, improve circulation, and promote relaxation.', 'Easy', 'multi'),
  ('cold-therapy', 'Cryotherapy (Cold Therapy)', 'Passive Therapy', 'Application of cold to reduce inflammation, pain, and muscle spasm following activity or injury.', 'Easy', 'multi'),
  ('heat-therapy', 'Thermotherapy (Heat Therapy)', 'Passive Therapy', 'Application of heat to increase tissue extensibility, reduce pain, and promote relaxation before activity.', 'Easy', 'multi'),
  ('stretch-quad', 'Quadriceps Stretch', 'Passive Therapy', 'Passive stretching of quadriceps muscle group to maintain/improve stifle flexion range.', 'Easy', 'multi'),
  ('stretch-hams', 'Hamstring Stretch', 'Passive Therapy', 'Passive stretching of hamstring muscle group to improve hip flexion and reduce muscle tightness.', 'Easy', 'multi'),
  ('effleurage', 'Lymphatic Effleurage', 'Passive Therapy', 'Light stroking massage technique to promote lymphatic drainage and reduce post-operative swelling.', 'Easy', 'multi'),
  ('sit-stand', 'Sit-to-Stand Transitions', 'Active Assisted', 'Controlled sitting and standing to strengthen hindlimb muscles and improve weight-bearing.', 'Easy', 'multi'),
  ('weight-shift', 'Weight Shifting Exercises', 'Active Assisted', 'Dynamic weight transfer exercises to improve balance, proprioception, and limb loading.', 'Easy', 'multi'),
  ('slow-walk', 'Controlled Slow Walking', 'Active Assisted', 'Deliberate slow-paced walking to promote proper gait mechanics and weight bearing.', 'Easy', 'multi'),
  ('stand-tall', 'Standing Tall (Rear Leg Dance)', 'Active Assisted', 'Rear limb strengthening by having dog stand on hindlimbs with forelimbs elevated.', 'Moderate', 'multi'),
  ('curb-walk', 'Curb/Step Walking', 'Active Assisted', 'Walking up and down small curbs or steps to improve joint flexion and strength.', 'Moderate', 'multi'),
  ('figure-8', 'Figure-Eight Walking', 'Active Assisted', 'Walking in figure-eight pattern to promote lateral flexion and improved proprioception.', 'Moderate', 'multi'),
  ('backing-up', 'Backing Up Exercise', 'Active Assisted', 'Controlled backward walking to engage different muscle groups and improve coordination.', 'Moderate', 'multi'),
  ('side-step', 'Side-Stepping (Lateral Walking)', 'Active Assisted', 'Lateral movement to strengthen hip abductors/adductors and improve lateral balance.', 'Moderate', 'multi'),
  ('slow-trot', 'Controlled Slow Trot', 'Active Assisted', 'Progression from walking to slow trotting gait to increase cardiovascular demand and strength.', 'Moderate', 'multi'),
  ('stair-climb', 'Stair Climbing (Assisted)', 'Active Assisted', 'Controlled stair ascent and descent to build hindlimb strength and improve joint range of motion.', 'Advanced', 'multi'),
  ('three-leg-stand', 'Three-Legged Standing', 'Strengthening', 'Isometric strengthening by having dog hold weight on three legs while one limb is lifted.', 'Moderate', 'multi'),
  ('cavaletti-rails', 'Cavaletti Rails', 'Strengthening', 'Walking over raised poles to improve joint flexion, proprioception, and coordination.', 'Moderate', 'multi'),
  ('sit-stand-wall', 'Sit-Stands Against Wall', 'Strengthening', 'Sit-stand transitions with rear positioned against wall to prevent rocking and ensure proper form.', 'Moderate', 'multi'),
  ('hill-climb', 'Hill Walking (Uphill)', 'Strengthening', 'Walking up inclines to build hindlimb strength and improve cardiovascular fitness.', 'Advanced', 'multi'),
  ('down-stand', 'Down-to-Stand Transitions', 'Strengthening', 'Moving from down position to standing to strengthen all limbs and core.', 'Advanced', 'multi'),
  ('wheel-barrel', 'Wheelbarrow Walking', 'Strengthening', 'Walking on forelimbs only with hindlimbs supported to strengthen shoulders and core.', 'Advanced', 'multi'),
  ('stair-run', 'Stair Running (Advanced)', 'Strengthening', 'Dynamic stair climbing at faster pace for advanced strengthening and power development.', 'Advanced', 'multi'),
  ('resist-walk', 'Resisted Walking', 'Strengthening', 'Walking against resistance to build muscular strength and endurance.', 'Advanced', 'multi'),
  ('jump-board', 'Jump Board Exercise', 'Strengthening', 'Jumping onto elevated platform to develop explosive power and hindlimb strength.', 'Advanced', 'multi'),
  ('pole-weave', 'Pole Weaving', 'Strengthening', 'Weaving through poles to strengthen core, improve lateral flexibility and coordination.', 'Advanced', 'multi'),
  ('trot-circles', 'Circle Trotting', 'Strengthening', 'Trotting in circles to strengthen inside hindlimb and improve balance during turns.', 'Advanced', 'multi'),
  ('backward-hill', 'Backward Hill Walking', 'Strengthening', 'Walking backwards up incline for advanced quadriceps and core strengthening.', 'Advanced', 'multi'),
  ('wobble-board', 'Wobble Board Training', 'Balance & Proprioception', 'Standing on unstable platform to improve balance, proprioception, and core stability.', 'Moderate', 'multi'),
  ('balance-pad', 'Balance Pad Exercises', 'Balance & Proprioception', 'Standing or performing exercises on foam pad to challenge balance and proprioception.', 'Moderate', 'multi'),
  ('physio-ball', 'Physioball (Peanut Ball) Exercises', 'Balance & Proprioception', 'Core strengthening and balance training using inflatable peanut-shaped ball.', 'Advanced', 'multi'),
  ('blindfold-walk', 'Proprioceptive Walking (Visual Restriction)', 'Balance & Proprioception', 'Walking with reduced visual input to enhance proprioceptive awareness.', 'Moderate', 'multi'),
  ('uneven-terrain', 'Uneven Terrain Walking', 'Balance & Proprioception', 'Walking on varied surfaces to challenge proprioception and balance reactions.', 'Moderate', 'multi'),
  ('ball-nudge', 'Ball Nudging Exercise', 'Balance & Proprioception', 'Pushing large ball with nose/paws to improve coordination and spatial awareness.', 'Moderate', 'multi'),
  ('surface-change', 'Surface Transition Exercise', 'Balance & Proprioception', 'Walking across different surface types to improve proprioceptive awareness and adaptation.', 'Moderate', 'multi'),
  ('perturbation', 'Perturbation Training', 'Balance & Proprioception', 'Gentle unexpected balance challenges to improve reactive balance responses.', 'Advanced', 'multi'),
  ('laser-chase', 'Laser Pointer/Target Following', 'Balance & Proprioception', 'Following moving target to improve coordination, focus, and dynamic balance.', 'Moderate', 'multi'),
  ('slow-pivot', 'Slow Pivot Turns', 'Balance & Proprioception', 'Rotating in place to improve proprioception, balance, and coordination.', 'Moderate', 'multi'),
  ('underwater-tread', 'Underwater Treadmill Walking', 'Aquatic Therapy', 'Walking on submerged treadmill for low-impact strengthening and range of motion.', 'Moderate', 'multi'),
  ('pool-swim', 'Therapeutic Swimming', 'Aquatic Therapy', 'Free swimming for cardiovascular fitness and full-body strengthening with minimal joint stress.', 'Moderate', 'multi'),
  ('water-walking', 'Shallow Water Walking', 'Aquatic Therapy', 'Walking in shallow water (belly to mid-chest depth) for gentle resistance training.', 'Moderate', 'multi'),
  ('water-retrieve', 'Water Retrieval Exercise', 'Aquatic Therapy', 'Fetching objects in water to combine cardiovascular exercise with motivation and fun.', 'Moderate', 'multi'),
  ('aqua-jog', 'Aqua Jogging', 'Aquatic Therapy', 'Jogging in chest-deep water for advanced cardiovascular and strengthening work.', 'Advanced', 'multi'),
  ('car-entry', 'Car Entry/Exit Practice', 'Functional Training', 'Practicing getting in and out of vehicles safely to restore functional independence.', 'Moderate', 'multi'),
  ('couch-on-off', 'Furniture Climbing (Couch/Bed)', 'Functional Training', 'Getting on and off furniture safely to restore normal household function.', 'Moderate', 'multi'),
  ('door-threshold', 'Door Threshold Navigation', 'Functional Training', 'Stepping over door thresholds and transitions to restore household mobility.', 'Easy', 'multi'),
  ('play-bow', 'Play Bow Stretch', 'Functional Training', 'Natural play bow position for shoulder stretching and functional movement pattern.', 'Easy', 'multi'),
  ('greeting-sit', 'Controlled Greeting/Sitting', 'Functional Training', 'Practicing calm sitting for greetings to restore social function and impulse control.', 'Moderate', 'multi'),
  ('bosu-stand', 'BOSU Ball Static Standing', 'Balance & Proprioception', 'Advanced balance training using BOSU ball to challenge proprioceptive awareness and core stabilization on unstable surface.', 'Advanced', 'multi'),
  ('wobble-board-adv', 'Advanced Wobble Board Training', 'Balance & Proprioception', 'Multi-directional balance challenge using rocker board to improve dynamic stability and weight shifting.', 'Advanced', 'multi'),
  ('foam-pad-stand', 'Foam Pad Static Standing', 'Balance & Proprioception', 'Proprioceptive training on dense foam to enhance sensory feedback and postural control.', 'Moderate', 'multi'),
  ('cavaletti-var', 'Variable Height Cavaletti Work', 'Balance & Proprioception', 'Advanced gait training using cavaletti poles at varying heights to enhance limb awareness and coordination.', 'Moderate', 'multi'),
  ('theraband-wts', 'TheraBand Weight Shifting', 'Balance & Proprioception', 'Controlled lateral and forward weight shifts using resistance band to challenge dynamic balance and core strength.', 'Moderate', 'multi'),
  ('figure8-cone', 'Figure-8 Cone Weaving', 'Balance & Proprioception', 'Advanced coordination exercise requiring tight turns and weight shifts through serpentine pattern.', 'Moderate', 'multi'),
  ('perturbation-adv', 'Advanced Controlled Perturbation Training', 'Balance & Proprioception', 'Manual application of unexpected balance challenges to improve reactive postural responses.', 'Advanced', 'multi'),
  ('blindfold-bal', 'Blindfold Balance (Visual Deprivation)', 'Balance & Proprioception', 'Advanced proprioceptive training eliminating visual compensation to enhance somatosensory reliance.', 'Advanced', 'multi'),
  ('diagonal-lift', 'Diagonal Limb Lift Holds', 'Balance & Proprioception', 'Three-legged standing balance with diagonal limb elevation to challenge core stability and contralateral limb loading.', 'Advanced', 'multi'),
  ('platform-trans', 'Platform-to-Platform Transitions', 'Balance & Proprioception', 'Dynamic balance training requiring controlled stepping between elevated platforms of varying heights.', 'Advanced', 'multi'),
  ('tens-therapy', 'TENS (Transcutaneous Electrical Nerve Stimulation)', 'Therapeutic Modalities', 'Application of low-voltage electrical current through skin to modulate pain perception and promote muscle re-education.', 'Moderate', 'multi'),
  ('nmes-quad', 'NMES (Neuromuscular Electrical Stimulation) - Quadriceps', 'Therapeutic Modalities', 'High-intensity electrical stimulation to prevent muscle atrophy and maintain muscle mass in quadriceps during immobilization or disuse.', 'Moderate', 'multi'),
  ('us-pulsed', 'Therapeutic Ultrasound (Pulsed Mode)', 'Therapeutic Modalities', 'Application of pulsed ultrasound waves to promote tissue healing without thermal effects, ideal for acute injuries.', 'Moderate', 'multi'),
  ('us-continuous', 'Therapeutic Ultrasound (Continuous Mode)', 'Therapeutic Modalities', 'Continuous ultrasound application to increase tissue temperature and extensibility before stretching in chronic conditions.', 'Moderate', 'multi'),
  ('laser-iv', 'Class IV Laser Therapy', 'Therapeutic Modalities', 'High-powered laser photobiomodulation to reduce pain, inflammation, and accelerate tissue healing through cellular stimulation.', 'Moderate', 'multi'),
  ('pemf-therapy', 'Pulsed Electromagnetic Field (PEMF) Therapy', 'Therapeutic Modalities', 'Application of electromagnetic fields to enhance bone healing, reduce pain, and decrease inflammation through cellular mechanisms.', 'Easy', 'multi'),
  ('hydro-whirl', 'Hydrotherapy Whirlpool', 'Therapeutic Modalities', 'Warm water immersion with jet agitation to enhance circulation, promote wound healing, and reduce edema.', 'Moderate', 'multi'),
  ('ice-massage', 'Ice Massage', 'Therapeutic Modalities', 'Direct application of ice in circular massage pattern to reduce acute inflammation, pain, and muscle spasm.', 'Easy', 'multi'),
  ('contrast-bath', 'Contrast Therapy (Alternating Hot/Cold)', 'Therapeutic Modalities', 'Alternating immersion in warm and cold water to create vascular pumping effect for chronic edema and circulation enhancement.', 'Moderate', 'multi'),
  ('compression-tx', 'Compression Therapy', 'Therapeutic Modalities', 'Application of graduated compression bandaging to control edema, support tissues, and enhance lymphatic drainage.', 'Moderate', 'multi'),
  ('joint-mob-g1', 'Joint Mobilization - Grade I (Stifle)', 'Manual Therapy', 'Small amplitude oscillatory movements at beginning of range to reduce pain through mechanoreceptor stimulation.', 'Moderate', 'multi'),
  ('joint-mob-g2', 'Joint Mobilization - Grade II (Stifle)', 'Manual Therapy', 'Large amplitude oscillations within available range to reduce pain and improve joint play without stretching tissues.', 'Moderate', 'multi'),
  ('joint-mob-g3', 'Joint Mobilization - Grade III (Stifle)', 'Manual Therapy', 'Large amplitude oscillations into tissue resistance to stretch periarticular structures and break adhesions.', 'Advanced', 'multi'),
  ('myofasc-ilio', 'Myofascial Release - Iliopsoas', 'Manual Therapy', 'Sustained pressure and stretching of iliopsoas muscle and fascia to release hip flexor tension and improve hip extension.', 'Advanced', 'multi'),
  ('myofasc-bf', 'Myofascial Release - Biceps Femoris', 'Manual Therapy', 'Manual fascial stretching and release of biceps femoris to address hamstring tension and improve stifle ROM.', 'Moderate', 'multi'),
  ('uwtt-forward', 'Underwater Treadmill - Forward Walking', 'Hydrotherapy', 'Controlled forward walking in underwater treadmill utilizing buoyancy and resistance for controlled loading and cardiovascular conditioning.', 'Moderate', 'multi'),
  ('uwtt-backward', 'Underwater Treadmill - Backward Walking (Retrograde)', 'Hydrotherapy', 'Backward walking in UWTM to activate hip extensors, increase stifle flexion, and improve proprioceptive awareness.', 'Advanced', 'multi'),
  ('uwtt-lateral', 'Underwater Treadmill - Lateral Walking (Side-stepping)', 'Hydrotherapy', 'Side-stepping in UWTM to strengthen hip abductors/adductors and improve lateral stability.', 'Advanced', 'multi'),
  ('pool-swim-hydro', 'Pool Swimming - Freestyle', 'Hydrotherapy', 'Controlled swimming in therapy pool for cardiovascular conditioning, full body range of motion, and non-weight bearing exercise.', 'Moderate', 'multi'),
  ('pool-treading', 'Deep Water Treading', 'Hydrotherapy', 'Stationary treading in deep water to maximize cardiovascular demand and promote full range joint movement without weight bearing.', 'Advanced', 'multi'),
  ('hydro-jets', 'Underwater Jet Resistance Walking', 'Hydrotherapy', 'Walking against directed water jets in underwater treadmill to increase muscle activation and cardiovascular demand.', 'Advanced', 'multi'),
  ('wading-walk', 'Shallow Water Wading', 'Hydrotherapy', 'Walking in shallow water (ankle to mid-thigh depth) for gentle weight bearing reduction while maintaining proprioceptive input.', 'Easy', 'multi'),
  ('aqua-cavaletti', 'Submerged Cavaletti Walking', 'Hydrotherapy', 'Walking over submerged poles/obstacles in water to enhance limb flexion and proprioception with reduced weight bearing.', 'Moderate', 'multi'),
  ('aqua-weave', 'Underwater Weave Poles', 'Hydrotherapy', 'Weaving through vertical poles in water to promote lateral flexibility, core engagement, and coordination.', 'Advanced', 'multi'),
  ('aqua-fetch', 'Underwater Fetch and Retrieve', 'Hydrotherapy', 'Retrieving submerged objects to encourage diving motion, neck/thoracic extension, and breath control.', 'Advanced', 'multi'),
  ('hydro-balance', 'Aquatic Balance Board', 'Hydrotherapy', 'Standing balance work on submerged platform or board to enhance proprioception with reduced fall risk.', 'Advanced', 'multi'),
  ('aqua-stand', 'Static Water Standing', 'Hydrotherapy', 'Standing balance in water with manual perturbations to improve weight bearing tolerance and core stability.', 'Moderate', 'multi'),
  ('aqua-steps', 'Submerged Step-Ups', 'Hydrotherapy', 'Stepping up and down on submerged platform to promote controlled weight bearing and eccentric muscle control.', 'Moderate', 'multi'),
  ('aqua-circles', 'Tight Circle Walking in Water', 'Hydrotherapy', 'Walking small diameter circles in water to increase inside limb loading and core rotational strength.', 'Moderate', 'multi'),
  ('aqua-plank', 'Aquatic Plank Hold', 'Hydrotherapy', 'Front paws elevated on pool edge while hindlimbs tread water to promote core strength and hindlimb muscle activation.', 'Advanced', 'multi'),
  ('gentle-prom', 'Geriatric-Adapted Passive ROM', 'Geriatric Care', 'Extra gentle passive range of motion specifically adapted for geriatric patients with arthritis and reduced tissue tolerance.', 'Easy', 'multi'),
  ('senior-walk', 'Slow Controlled Leash Walking', 'Geriatric Care', 'Short, frequent walking sessions tailored to geriatric mobility and endurance limitations.', 'Easy', 'multi'),
  ('massage-senior', 'Therapeutic Massage for Seniors', 'Geriatric Care', 'Gentle massage techniques to improve circulation, reduce muscle tension, and provide pain relief for geriatric patients.', 'Easy', 'multi'),
  ('sit-stand-senior', 'Geriatric Sit-to-Stand Transitions', 'Geriatric Care', 'Controlled sit-to-stand exercises modified for senior dogs to maintain functional mobility and hindlimb strength.', 'Easy', 'multi'),
  ('senior-balance', 'Gentle Balance Training for Seniors', 'Geriatric Care', 'Modified standing balance work to prevent falls and maintain proprioceptive awareness in geriatric patients.', 'Easy', 'multi'),
  ('raised-feed', 'Elevated Feeding Position Therapy', 'Geriatric Care', 'Using elevated feeding as therapeutic positioning to reduce neck/spine flexion and promote better posture during daily activities.', 'Easy', 'multi'),
  ('ramp-training', 'Ramp Training for Mobility', 'Geriatric Care', 'Teaching safe ramp use for accessing furniture and vehicles, reducing jump stress on joints.', 'Easy', 'multi'),
  ('heat-therapy-geri', 'Therapeutic Heat Application', 'Geriatric Care', 'Moist heat therapy to reduce muscle tension, improve circulation, and provide pain relief before exercise.', 'Easy', 'multi'),
  ('cold-therapy-geri', 'Therapeutic Cold Application', 'Geriatric Care', 'Cryotherapy for managing acute inflammation and pain in geriatric arthritis flare-ups.', 'Easy', 'multi'),
  ('bedding-exercise', 'Therapeutic Bed Positioning', 'Geriatric Care', 'Orthopedic bedding and positioning to maintain joint alignment and comfort during rest.', 'Easy', 'multi')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;