import { useState, useEffect } from "react";
// Auth-aware axios — raw axios bypasses JWT and 401s.
import api, { API } from "../../api/axios";

export function useSettingsState(setBrand, toast) {
  // ── Clinic profile (persisted to API) ──
  const [form, setForm] = useState({
    clinic_name: "", logo_url: "", primary_color: "#0F4C81",
    secondary_color: "#0EA5E9", contact_email: "", phone: "", address: "",
    website: "", license_number: "", dea_number: "",
    clinic_type: "specialty_referral",
  });
  const [clinicId, setClinicId] = useState(null);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);

  // ── Settings tab ──
  const [activeTab, setActiveTab] = useState("clinic");

  // ── Clinician credentials (client-side) ──
  const [clinician, setClinician] = useState({
    name: "", title: "DVM", credentials: [], license_number: "",
    license_state: "", npi: "", board_certs: [],
  });

  // ── Equipment is NOT held here any more, 2026-09-26 ──
  //
  // It was a client-side object with its own vocabulary — underwater_treadmill,
  // therapeutic_pool, class_iv_laser — that shared NOT ONE KEY with the
  // engine's (aquatic_access, modality_uwtm, modality_laser, ...), and nothing
  // ever saved it anywhere. Every toggle was a no-op while the tab displayed
  // "Equipment settings gate protocol generation — exercises requiring
  // unavailable equipment will be excluded automatically".
  //
  // Measured the day it was removed: the clinic had 10 of 10 capabilities
  // unstated, so every gated therapy was being withheld from every protocol
  // for every patient, and the one screen a clinician would open to fix that
  // was connected to nothing.
  //
  // TabEquipment now reads and writes /v2/clinic/capabilities directly, which
  // is the store the protocol engine actually reads. A copy here would make it
  // two stores for one fact again.

  // ── Protocol defaults (client-side) ──
  const [protocolDefaults, setProtocolDefaults] = useState({
    progression_philosophy: "moderate",
    session_duration: 45,
    sessions_per_week: 3,
    pain_threshold_hold: 4,
    weight_bearing_threshold: "partial",
    include_hep: true,
    default_outcome_measure: "cbpi",
    auto_progression_gates: true,
    recheck_interval_weeks: 2,
  });

  // ── Documentation & reports (client-side) ──
  const [docSettings, setDocSettings] = useState({
    include_citations: true,
    include_json_blocks: false,
    logo_on_reports: true,
    default_export_format: "pdf",
    report_header: "",
    report_footer: "Generated by K9 Rehab Pro\u2122 \u00b7 B.E.A.U. AI \u2014 Biomedical Evidence-based Analytical Unit for Canine and Feline Rehabilitation",
    include_contraindications: true,
    include_progression_criteria: true,
  });

  // ── Notifications (client-side) ──
  const [notifications, setNotifications] = useState({
    phase_progression_reminders: true,
    recheck_reminders: true,
    pain_threshold_alerts: true,
    protocol_expiration_alerts: true,
    session_completion_tracking: true,
    reminder_lead_days: 3,
  });

  // ── Security (client-side) ──
  const [security, setSecurity] = useState({
    session_timeout_minutes: 30,
    audit_log_enabled: true,
    auto_lock_screen: true,
    data_retention_years: 7,
  });

  // ── Appearance (client-side) ──
  const [appearance, setAppearance] = useState({
    font_size: "standard",
    exercise_card_display: "detailed",
    dashboard_layout: "standard",
  });

  // ── Section expand states ──
  const [expanded, setExpanded] = useState({});
  const toggleSection = (key) => setExpanded(prev => ({ ...prev, [key]: !prev[key] }));
  const isOpen = (id) => expanded[id] !== false;

  // ── Load clinic data ──
  useEffect(() => {
    api.get(`/clinics`).then(r => {
      const clinic = r.data?.[0];
      if (clinic) {
        setClinicId(clinic.id);
        setForm(prev => ({ ...prev, ...clinic }));
        setBrand(b => ({ ...b, clinicName: clinic.clinic_name, accent: clinic.primary_color }));
      }
    }).catch(() => { /* Endpoint not yet configured — form uses defaults */ });
  }, [setBrand]);

  // ── Save clinic profile ──
  const saveClinic = async () => {
    setSaving(true);
    try {
      if (clinicId) {
        await api.put(`/clinics/${clinicId}`, form);
      } else {
        const { data } = await api.post(`/clinics`, form);
        setClinicId(data.id);
      }
      setBrand(b => ({ ...b, clinicName: form.clinic_name, accent: form.primary_color }));
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (e) { console.error("Save failed", e); }
    setSaving(false);
  };

  // ── Save any section (client-side flash) ──
  const flashSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  return {
    // Clinic
    form, setForm, clinicId, saved, saving, saveClinic,
    // Tab
    activeTab, setActiveTab,
    // Clinician
    clinician, setClinician,
    // Equipment is not here: TabEquipment owns it and talks to
    // /v2/clinic/capabilities directly. See the note above.
    // Protocol defaults
    protocolDefaults, setProtocolDefaults,
    // Documentation
    docSettings, setDocSettings,
    // Notifications
    notifications, setNotifications,
    // Security
    security, setSecurity,
    // Appearance
    appearance, setAppearance,
    // Section expand
    expanded, toggleSection, isOpen,
    // Actions
    flashSave,
  };
}
