import React, { useState } from "react";
import { FiCopy, FiPrinter, FiChevronDown, FiChevronRight, FiFileText } from "react-icons/fi";

/**
 * Renders a structured clinical document within the chat.
 * Receives parsed JSON from :::document blocks in B.E.A.U. responses.
 */
export default function NarrativePanel({ document: doc }) {
  const [expandedSections, setExpandedSections] = useState(
    new Set((doc?.sections || []).map((_, i) => i))
  );
  const [copied, setCopied] = useState(false);

  if (!doc || !doc.sections) return null;

  const toggleSection = (idx) => {
    setExpandedSections(prev => {
      const next = new Set(prev);
      next.has(idx) ? next.delete(idx) : next.add(idx);
      return next;
    });
  };

  const copyToClipboard = () => {
    const text = doc.sections.map(s => `## ${s.heading}\n\n${s.content}`).join("\n\n---\n\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  // HTML-escape helper — critical for XSS safety. `doc` is AI-generated
  // text that could contain `<script>`; interpolating raw into document.write
  // opens the print-preview window (same origin → session/token theft).
  const esc = (s) => String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

  const printDocument = () => {
    const title = esc(doc.title || "Clinical Document");
    const dateStr = esc(new Date().toLocaleDateString());
    const html = doc.sections.map(s =>
      `<h2 style="color:#1A5F8A;border-bottom:1px solid #ddd;padding-bottom:4px">${esc(s.heading)}</h2><div style="white-space:pre-wrap;line-height:1.6">${esc(s.content)}</div>`
    ).join("<hr style='margin:16px 0'>");

    const win = window.open("", "_blank");
    win.document.write(`<html><head><title>${title}</title><style>body{font-family:Inter,system-ui,sans-serif;padding:32px;max-width:800px;margin:0 auto;font-size:13px;color:#333}h2{font-size:15px;margin-top:20px}</style></head><body><h1 style="color:#0F4C81;font-size:18px">${title}</h1><p style="color:#888;font-size:11px">Generated by K9 Rehab Pro CDSS &bull; ${dateStr}</p>${html}<p style="margin-top:24px;padding-top:12px;border-top:1px solid #ddd;color:#888;font-size:10px;font-style:italic">This document must be reviewed and approved by a licensed veterinarian before clinical application.</p></body></html>`);
    win.document.close();
    win.print();
  };

  return (
    <div style={{
      margin: "12px 0", borderRadius: 10, overflow: "hidden",
      border: "1px solid var(--k9-border)", background: "var(--k9-surface)",
    }}>
      {/* Header */}
      <div style={{
        padding: "10px 14px", display: "flex", alignItems: "center", justifyContent: "space-between",
        background: "var(--k9-bg)", borderBottom: "1px solid var(--k9-border)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <FiFileText style={{ color: "var(--k9-teal)", width: 16, height: 16 }} />
          <span style={{ fontWeight: 700, fontSize: 13, color: "var(--k9-text)" }}>
            {doc.title || doc.templateName || "Clinical Document"}
          </span>
          {doc.type && (
            <span style={{
              fontSize: 10, padding: "2px 6px", borderRadius: 4,
              background: "var(--k9-teal)", color: "#fff", fontWeight: 600,
            }}>
              {doc.type.replace(/_/g, " ").toUpperCase()}
            </span>
          )}
        </div>
        <div style={{ display: "flex", gap: 6 }}>
          <button onClick={copyToClipboard} style={{
            padding: "4px 8px", borderRadius: 4, border: "1px solid var(--k9-border)",
            background: copied ? "var(--k9-teal)" : "transparent",
            color: copied ? "#fff" : "var(--k9-text-light)",
            fontSize: 11, cursor: "pointer", display: "flex", alignItems: "center", gap: 4,
          }}>
            <FiCopy size={11} /> {copied ? "Copied" : "Copy"}
          </button>
          <button onClick={printDocument} style={{
            padding: "4px 8px", borderRadius: 4, border: "1px solid var(--k9-border)",
            background: "transparent", color: "var(--k9-text-light)",
            fontSize: 11, cursor: "pointer", display: "flex", alignItems: "center", gap: 4,
          }}>
            <FiPrinter size={11} /> Print
          </button>
        </div>
      </div>

      {/* Sections */}
      <div style={{ padding: "4px 0" }}>
        {doc.sections.map((section, idx) => (
          <div key={idx} style={{ borderBottom: idx < doc.sections.length - 1 ? "1px solid var(--k9-border)" : "none" }}>
            <button
              onClick={() => toggleSection(idx)}
              style={{
                width: "100%", padding: "8px 14px", display: "flex", alignItems: "center", gap: 6,
                background: "transparent", border: "none", cursor: "pointer", textAlign: "left",
              }}
            >
              {expandedSections.has(idx)
                ? <FiChevronDown style={{ color: "var(--k9-teal)", width: 12, height: 12, flexShrink: 0 }} />
                : <FiChevronRight style={{ color: "var(--k9-text-light)", width: 12, height: 12, flexShrink: 0 }} />
              }
              <span style={{
                fontWeight: 600, fontSize: 12,
                color: expandedSections.has(idx) ? "var(--k9-teal)" : "var(--k9-text)",
              }}>
                {section.heading}
              </span>
            </button>
            {expandedSections.has(idx) && (
              <div style={{
                padding: "4px 14px 12px 32px", fontSize: 12, lineHeight: 1.65,
                color: "var(--k9-text)", whiteSpace: "pre-wrap",
              }}>
                {section.content}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer disclaimer */}
      <div style={{
        padding: "8px 14px", fontSize: 10, color: "var(--k9-text-light)",
        borderTop: "1px solid var(--k9-border)", fontStyle: "italic",
        background: "var(--k9-bg)",
      }}>
        CDSS-generated document. Must be reviewed and approved by a licensed veterinarian.
      </div>
    </div>
  );
}
